### ISSUE TITLE
How to transfer arguments to WebAssembly binary generated from C?

### ISSUE THREAD

**Issue by kimdora** [bytecodealliance/wasmtime-dotnet#104]
Hello, I converted below C code to WebAssembly binary using [`wasi-sdk-14`](https://github.com/WebAssembly/wasi-sdk/releases) (I downloaded `wasi-sdk-14.0-macos.tar.gz`)

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main (int argc, char ** argv) {
    char * buf = (char *) malloc(100);
    memcpy(buf, argv[1], 100);
    printf("buf: %s\n", buf); 
    return 0;
}
```

And I am using below script to run the WebAssembly binary file which name is `prog.wasm`.
```f#
open System
open Wasmtime

[<EntryPoint>]
let main _ =
  let path = "prog.wasm"
  let engine = new Engine()
  let wm = Module.FromFile(engine, path)
  let linker = new Linker(engine)
  let store = new Store(engine)

  let cfg = new WasiConfiguration()

  linker.DefineWasi()
  store.SetWasiConfiguration(cfg)

  let instance = linker.Instantiate(store, wm)
  let func = instance.GetFunction(store, "_start")
  let result = func.Invoke(store)
  0
```

What I want is to transfer arguments to the binary. But `_start` function does not have any arguments.
I guess `_start` function is entry point of code which executes `main` function...

So my question is how to transfer arguments to the binary generated from C code?
Additionally, I also wonder that how to pass standard input.

**Comment by iwate** [comment]
I think `WithArgs` can do it.
```
let cfg = new WasiConfiguration().WithArgs("--", "Hello,World!")
```

This is my code for learning. I hope this will help.
https://github.com/iwate/learn-wasm-with-dotnet/blob/ede974d438e908bb36eb6587bbd3e6835cf96836/challenge04/dotnet/Iwate.WasmtimeChallenge04/Program.cs#L56

**Comment by kimdora** [comment]
And I also wonder that what is difference between `WithArgs` and `WithInheritedArgs`.

**Comment by iwate** [comment]
@kimdora 

When you add `WithInheritedArgs()` config, the args of your app will be passed to wasmtime. 
So, `WithInheritedArgs()` equals to `.WithArgs(Environment.GetCommandLineArgs())`
https://github.com/bytecodealliance/wasmtime-dotnet/blob/9fad6c4e5918798c9b221e42980c6e524984f54c/src/WasiConfiguration.cs#L96

If you exec the screenshot's program, you can get this output.

```
[|"C:\Users\iwate\works\iwate\WasmtimeSample\WasmtimeSample\bin\Debug\net6.0\WasmtimeSample.dll";
  "Hello"|]
buf: Hello
```
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1011232/161985522-dc4bc699-4713-4607-b526-d2af846fbe61.png">

So, `--` is placeholder for arg0 which is insted of `path/to/the/app.dll`.

**Comment by kimdora** [comment]
Oh, thanks to your explaination, I understand it!
Thank you.
