### ISSUE TITLE
Manually consume fuel from store

### ISSUE THREAD

**Issue by my0n** [bytecodealliance/wasmtime-dotnet#106]
Is it possible to manually consume fuel from the store? Looks like adding fuel and getting the current amount of consumed fuel is supported, but I wanted to put an extra cost to some of the functions that I'm calling.

I'm very new to wasm stuff in general, but it looks like this should be possible using [Store::consume_fuel](https://docs.wasmtime.dev/api/wasmtime/struct.Store.html#method.consume_fuel) - calling that function seems straightforward so I may be able to take a swing at this if you'd like

**Comment by peterhuene** [comment]
Hi @my0n. Indeed, `Store::consume_fuel` would be the way to do this. It is exposed in Wasmtime's C API as `wasmtime_context_consume_fuel`, so it should be usable from the .NET API with a P/Invoke added.

It would be wonderful if you could take a stab at adding support for it and putting up a PR; I'm happy to help if you run into any problems!

**Comment by my0n** [comment]
Opened up a PR! Also thanks for the library, it's very clean and easy to use

**Comment by peterhuene** [comment]
Implemented in #107.
