### ISSUE TITLE
Question: NaN canonicalization

### ISSUE THREAD

**Issue by mralexes** [bytecodealliance/wasmtime-dotnet#109]
Is there a way to enable the canonicalization of NaNs? As I see it is supported by the underlying library https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.cranelift_nan_canonicalization but I was not able to use it using this .NET package.

**Comment by peterhuene** [comment]
Unfortunately that setting is not exposed via Wasmtime's C API at the moment, so the .NET API can't expose it.

Would you mind filing an issue with the wasmtime repo to add it to the C API? Once that is fixed, I will expose it in the .NET API for you to use.

Thanks!

**Comment by mralexes** [comment]
@peterhuene I have updated C API in his PR https://github.com/bytecodealliance/wasmtime/pull/4154, please check

**Comment by peterhuene** [comment]
@mralexes thanks again for implementing this! The feature should be available if you do a clean build of the latest out of the `main` branch.

When Wasmtime publishes a new version, I'll likewise publish a new package to NuGet with the feature.
