### ISSUE TITLE
Question/Proposal `Function.IsWasi`

### ISSUE THREAD

**Issue by martindevans** [bytecodealliance/wasmtime-dotnet#124]
For my application I want to know if a given function is part of WASI (this is so I know that a particular WASM file is going to require WASI defined to work and also so that I can hide these functions from the UI). Is it possible to get this information somehow?

If not, I propose adding an `IsWasi` property to `Function`. I'm willing to write a PR for this if you think it's a good idea, but if so I'll need some guidance on how best to get the information from the underlying wasmtime system.

**Comment by peterhuene** [comment]
It should be possible to check if the module imports anything from a known WASI "module":

```c#
using var module = Module.FromFile("...");

if (module.Imports.Any(i => i.ModuleName == "wasi_snapshot_preview1"))
{
   // The module needs WASI...
}
```
