### ISSUE TITLE
Optional String Encoding of Memory

### ISSUE THREAD

**Issue by Joshhua5** [bytecodealliance/wasmtime-dotnet#133]
The memory layout of WASM strings compiled with AssemblyScript is in UTF16 format, while the memory.readstring functions are all hard coded to UTF8. https://github.com/AssemblyScript/assemblyscript/issues/1653

Providing an optional override for this format would be helpful, the temporary workaround is to encode strings within wasm, but ideally this could be avoided.

**Comment by peterhuene** [comment]
Hi @Joshhua5. I agree that it'd be best to have overloads to these methods that accept the encoding.

Would you like to contribute a patch for that? I would be happy to review it!
