### ISSUE TITLE
Does this repository use wasmtime underhood ?

### ISSUE THREAD

**Issue by redradist** [bytecodealliance/wasmtime-dotnet#14]
Seems like this repository have a separate implementation from https://github.com/bytecodealliance/wasmtime ?

I have not found any references to wasmtime written in Rust ...

Is it right ?
And if yes, why ? It is possible to runt from .NET native binaries such as wasmtime (rust) ...

**Comment by peterhuene** [comment]
Hi @redradist.  This repository is the official Wasmtime language bindings for .NET.

Internally, it uses the Wasmtime C API to load and execute Wasm modules.

I hope that helps answer any questions you have.

Please feel free to follow-up with any additional questions.  For now, I will close this issue.
