### ISSUE TITLE
`Function` instance passed to a callback (as `funcref`) cannot be called outside of the callback

### ISSUE THREAD

**Issue by kpreisser** [bytecodealliance/wasmtime-dotnet#200]
Currently, when a callback gets a `funcref` value, it will be created as a `Function` instance, using the `Caller` as `IStore`. However, the `Caller` is only valid within the callback, so it's not possible to store the `Function` and later call it outside of the callback.

Consider the following code:
```cs
using var engine = new Engine();
using var module1 = Module.FromText(
    engine,
    "hello",
    @"
(module 
    (import """" ""store_funcref"" (func $store_funcref (param funcref)))
    (export ""run"" (func $run))
    (elem declare func $getValue)
    (func $getValue (result i32)
        i32.const 123
    )
    (func $run 
        (call $store_funcref (ref.func $getValue))
    )
)");

using var linker = new Linker(engine);
using var store = new Store(engine);

var storedFuncRef = default(Function);
linker.DefineFunction("", "store_funcref", (Function? funcRef) =>
{
    storedFuncRef = funcRef;
});

var instance = linker.Instantiate(store, module1);

var run = instance.GetAction("run")!;
run();

var wrappedFuncRef = storedFuncRef!.WrapFunc<int>()!;
int result = wrappedFuncRef();
Console.WriteLine("Result: " + result);
```

**Expected behavior:**

Runs successfully and prints `Result: 123` to the console.

**Actual behavior:**

Throws an `ObjectDisposedException`, because the `Caller` is no longer usable.
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Wasmtime.Caller'.
   at Wasmtime.Caller.get_NativeHandle() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Caller.cs:line 92
   at Wasmtime.Caller.Wasmtime.IStore.get_Context() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Caller.cs:line 99
   at Wasmtime.Function.<>c__DisplayClass184_0`1.<WrapFunc>b__0() in C:\Users\VPC\Desktop\WebAssembly-Test\wasmtime-dotnet\src\Function.Wrap.cs:line 841
   at Program.<<Main>$>g__TestCallbackStoreFuncRef|0_9() in C:\Users\VPC\Desktop\WebAssembly-Test\TestWasmtime\Program.cs:line 669
   at Program.<Main>$(String[] args) in C:\Users\VPC\Desktop\WebAssembly-Test\TestWasmtime\Program.cs:line 687
```

<del>With the work done by #191, I was thinking to leverage the store data feature, and instead of storing the store's `Data` object, store the `Store` object itself in the context data, so that we can retrieve it from the caller and can use it to create `Function` instances that are still usable outside of the callback.</del>

**Comment by kpreisser** [comment]
Hi @peterhuene!
I would like to continue the discussion from the closed PR (#201) in this issue. (I apologize for the long text... :innocent: )

My motivation for this issue is the difference between a wasm function returning a value, and a host callback receiving a value. When a wasm function returns a `funcref`, it will be returned in the .NET API as `Function` using the `Store` of the called wasm function, so that it's possible to call the returned `Function` later. However, when a host callback receives a `Function`, it will use the `Caller` as `IStore`, so it is only usable within the callback / until the callback has returned.

For example, I can imagine host functions that can be used to register wasm callbacks (like adding an event handler), which would then get passed a `funcref` value. Here, I would expect that the `Function` that gets passed to the .NET callback function is still callable at a later time.

> With these changes, the native store always holds a root to the `Store` and the `Store` holds a handle to the native store, meaning it'll never be collected without an explicit `Dispose` call to free the root held by the native store.

It should be possible (unless I'm missing something) to fix the circular reference (that keeps the `Store` alive) simply by using a [weak `GCHandle`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandletype?view=net-6.0#system-runtime-interopservices-gchandletype-weak) for the `Store`, so that the allocated `GCHandle` doesn't participate in keeping the `Store` alive.
See commit (this is on top of PR #201): https://github.com/kpreisser/wasmtime-dotnet/commit/4a848c2ad733d334955d4912ed2bc6d5b5d66d5e

That way, if the `Store` and thus its `Store.Handle` are no longer referenced, they will be collected by the GC, triggering deletion of the native `wasmtime_store_t`, which in turn will eventually call the finalizer function that frees the `GCHandle`.

**Note:** For this to work (and also as general requirement when freeing handles in finalizers, independent from this change), the `Store` must be kept alive while its context is used in calling native functions, e.g. with `wasmtime_call_func`. This is needed even though `Function` contains a reference to the `Store`, as in theory, the .NET GC can be aggressive in freeing unreferenced objects, up to the point where an `this` pointer in an instance method is considered to no longer be alive while the instance method is still executing. See: https://github.com/dotnet/runtime/blob/798da0cd21f52f1ee56a5886608ad84a634441f6/src/coreclr/System.Private.CoreLib/src/System/GC.CoreCLR.cs#L245-L284

Otherwise, it could happen that the finalizer of `Store.Handle` releases the object (in this case by calling `wasmtime_store_delete`) in the GC finalizer thread, even if at the same time another thread calls `Function.Invoke(...)` that passes the store context handle.

This can be ensured by calling `GC.KeepAlive(...)` after the native function has returned. This is also the pattern .NET follows when calling native functions taking a handle that may be freed by a finalizer, for example: https://github.com/dotnet/winforms/blob/9184e02413ee442f30d2548db84088bb7336edcc/src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs#L1535-L1536

While this wouldn't be a problem when calling native functions that receive a `wasmtime_store_t*` as `Store.Handle` (as the `SafeHandle` will keep the handle alive during the call), functions like `wasmtime_call_func` don't use the `Store` handle, but a `wasmtime_context_t*`, and there, it might be possible that the `Store` is not kept alive during the call.
(I think this can be fixed with a separate PR, as this may be a general issue.)

> While it _is_ possible to reference a `Store` from a store data object _today_ and thus introduce the same circular reference, we should probably add a "don't do that unless you really know what you're doing" documentation warning somewhere.

Note that this problem would also be fixed by using the weak `GCHandle` (as in the above noted commit based on the PR): Referencing the `Store` from a store data object will then no longer prevent the `Store` from being garbage-collected.
(This wouldn't work though in the current state without the PR (where the context data is a `GCHandle` directly to the data object), as then the data object might be GCed.)

> Additionally, I'm not convinced we need to fix #200. Linker functions should not capture anything related to call context and should manipulate any state that should outlive the call via `Caller.GetData`. While in Rust it's easy to enforce this invariant thanks to its type system and the compiler's borrow-checker, it's unfortunately trivial to violate in a GC language like C# with zero warning.

Can you elaborate more on this? I understand it in such a way that because the `wasmtime_caller_t` is only valid within the callback being called, it (and data derived from it, such as the `wasmtime_context_t`) must not be used after the callback returned. However, the context data feature allows to set data on the original `wasmtime_store_t` which is then available from the caller's context in the callback.
Therefore, it seems logical for me to assume that a `wasmtime_caller_t` must have a relationship to a store, and that while the `wasmtime_caller_t` exists, the original `wasmtime_store_t` also exists. This means to me that if there is a way to map the caller back to the origin store (using the context data), it would be possible to interpret values such as `funcref` and `externref` that the callback receives as belonging to this origin store, and therefore be able to substitute the context retrieved from the caller with the context retrieved from that store when working with these values.

For example, when the callback receives a `funcref`, in the native API it gets passed as `wasmtime_func_t*`, which consists of an (function) index and a store index (`"Internal identifier of what store this belongs to, never zero."`), so it suggests that the received value is valid as long as the store is valid, which may be longer than the time the caller is valid.

> The "proper" way to fix this, in my opinion, is to go back to passing in the store context to use when invoking or wrapping a function, like in the Rust API. Thus `Function` would not have a store context association meaning that it could safely outlive the caller context to be called with another reference to the same store.

I'm not yet sure if I particularly like this option, as it seems to introduce more low-level API in the .NET wrapper that I would expect to be more a high-level API. For example, you could pass the "wrong" store to the function, and while that would probably fail safely if you just pass the wrong store of the same engine, I assume bad things  (such as ouf-of-bounds read/write due to the unchecked function calls) could happen if you accidentally pass a store belonging to a different engine (since as the `wasmtime_func_t` seems to be a relative index within the engine, Wasmtime probably wouldn't be able to detect a store from a different engine if it's using the same internal index).

What do you think?

Thank you!

**Comment by peterhuene** [comment]
After reviewing #206 a little, I think I'm warming to the idea of fixing this as you describe.

I think having store context data that stores both a weak reference to the `Store` and the (nullable) user-supplied store data makes sense.

Perhaps we should eliminate `IStore` as it exposes the (relatively-unsafe) internal `StoreContext` mechanism. `Caller` can then have a `Store` property that gets the original store reference and throws if the weak reference can't be upgraded.

All `IStore` usages are changed to `Store`.  `Store`-related objects created via `Caller`'s store context would then use the original store and can safely outlive the host call.

We fix (via #206) all the places where we must `GC.KeepAlive` the store reference used to obtain the `StoreContext` needed to perform the requested operations.

Hows that approach sound to you?

**Comment by kpreisser** [comment]
Hi @peterhuene,
thanks for your reply and your additional thoughts!

> How does that approach sound to you?

I think that sounds good! Just a question about this:

> I think having store context data that stores both a weak reference to the `Store` and the (nullable) user-supplied store data makes sense.

Do you mean like using a `GCHandle` for an object/tuple that contains a `WeakReference<Store> store` and a `object? userData` field?

What do you think about using a weak `GCHandle` directly for the `Store`, and store the user data in an `object? data` field within the `Store`, like it was done in the ealier draft (https://github.com/bytecodealliance/wasmtime-dotnet/compare/main...kpreisser:wasmtime-dotnet:get-store-from-caller)?
IMHO, that would be simpler (avoids two allocations) and would also work, and should avoid the circular reference issue that would keep the `Store` alive when the user data object contains a reference to the `Store`.



> Perhaps we should eliminate `IStore` as it exposes the (relatively-unsafe) internal `StoreContext` mechanism. `Caller` can then have a `Store` property that gets the original store reference

👍 

> and throws if the weak reference can't be upgraded

Do you mean to throw when the target object of the weak `GCHandle` or `WeakReference<T>` would be `null`, like done in https://github.com/kpreisser/wasmtime-dotnet/commit/4a848c2ad733d334955d4912ed2bc6d5b5d66d5e?

Thank you!

**Comment by peterhuene** [comment]
> What do you think about using a weak GCHandle directly for the Store, and store the user data in an object? data field within the Store?

👍 I think that would be okay, as we're going through the context data to get the original `Store` for `Caller` anyway, so whether Wasmtime keeps a reference on it or the .NET API does shouldn't particularly matter.

> Do you mean to throw when the target object of the weak GCHandle or WeakReference<T> would be null, like done in https://github.com/kpreisser/wasmtime-dotnet/commit/4a848c2ad733d334955d4912ed2bc6d5b5d66d5e?

Yes, exactly that.
