### ISSUE TITLE
Wasmtime.WasmtimeException: Unable to create a callback with a return type of type 'System.UInt32' (and also with Uint64)

### ISSUE THREAD

**Issue by viperscape** [bytecodealliance/wasmtime-dotnet#237]
I am calling a c# function from WASM that should return an unsigned int or long, but for some reason Wasmtime throws an exception at runtime. Signed int and long work fine.

**Comment by martindevans** [comment]
According to the AssemblyScript docs ([here](https://www.assemblyscript.org/types.html)) the `u32` and `u64` types in AssemblyScript become `i32` and `i64` in WebAssembly.
