### ISSUE TITLE
Does the document need to be updated?

### ISSUE THREAD

**Issue by zxyao145** [bytecodealliance/wasmtime-dotnet#261]
I am using Wasmtime 9.0.3, but I couldn't find the host object. Is it a problem with my usage or is the document outdated.

![image](https://github.com/bytecodealliance/wasmtime-dotnet/assets/24973084/534bb2e2-8be1-48b1-a225-81169d6f26f5)

**Comment by martindevans** [comment]
Yep that looks (very) outdated. Until that's fixed I'd suggest using the example [here](https://github.com/bytecodealliance/wasmtime-dotnet/tree/main/examples) instead.
