### ISSUE TITLE
Implement reference types for .NET embeddings.

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime-dotnet#27]
Now that the reference types proposal is implemented in Wasmtime, let's implement it for .NET embeddings!

This means fully supporting the ref values, ref value types, handling reference types in host functions, handling reference types when invoking Wasm functions, and properly rooting .NET GC heap references when passing in and out of WebAssembly.

**Comment by peterhuene** [comment]
Once this is implemented, we can release a 0.19.0 NuGet package.

**Comment by fitzgen** [comment]
FWIW, here is what it took to do this in the python API: https://github.com/bytecodealliance/wasmtime-py/pull/41/commits/b8532a4ab146c6d7bddfff814b78718835fb511e

We don't really integrate with the python reference counting collector, we just manually pin data that is referenced by an `externref` in a global map.

**Comment by peterhuene** [comment]
It'll be something similar for .NET, although we won't need to do any mapping ourselves.

We'll allocate a `GCHandle` that will act as the extern ref's value; the finalizer will free the `GCHandle`, allowing for collection provided the .NET object is no longer reachable.  The .NET object won't need to be pinned as the `GCHandle` can track it and WebAssembly never needs the physical address on the .NET GC heap.

**Comment by peterhuene** [comment]
I've got extern refs working for .NET embeddings, but I'm noticing that the finalizer isn't being invoked for:

* Host calls `wasmtime_externref_new_with_finalizer`, the internal ref count should be 1 for the returned value.
* Pass reference into Wasm function (reference not stored; function immediately returns).
* Host calls `wasm_val_delete` on the reference value.  This should be driving the reference count to 0 and thus invoking the finalizer.

I haven't debugged it yet, so I'll take a look on Monday.

**Comment by peterhuene** [comment]
So I'm seeing 6 increments and 5 decrements between a `wasm_func_call` invocation passing a ref value:

```
Creating extern ref with `wasmtime_externref_new_with_finalizer`.
Calling function...
Extern ref count: 1 -> 2
Extern ref count: 2 -> 3
Extern ref count: 3 -> 4
Extern ref count: 4 -> 5
Extern ref count: 5 -> 6
Extern ref count: 6 -> 5
Hello from C#, Peter!
Extern ref count: 5 -> 4
Extern ref count: 4 -> 3
Extern ref count: 3 -> 2
Wasm function returned...
Deleting previously created value with `wasm_val_delete`.
Extern ref count: 2 -> 1
```

The code:

```c#
using var engine = new EngineBuilder()
    .WithReferenceTypes(true)
    .Build();

using var module = Module.FromText(engine, "externref", @"
(module
  (import """" ""hello"" (func $.hello (param externref)))
  (func (export ""run"") (param externref)
    local.get 0
    call $.hello
  )
)");

using var host = new Host(engine);

host.DefineFunction(
    "",
    "hello",
    (string name) => Console.WriteLine($"Hello from C#, {name}!")
);

using dynamic instance = host.Instantiate(module);
instance.run("Peter");
```

And the value is thereby leaked.  I'm capturing the ref count stacks now.

**Comment by peterhuene** [comment]
increment: /home/peterhuene/src/wasmtime/crates/c-api/src/func.rs:213 (_wasmtime_func_call)
increment: /home/peterhuene/src/wasmtime/crates/wasmtime/src/func.rs:597 (Func::call)
increment: /home/peterhuene/src/wasmtime/crates/wasmtime/src/func.rs:279 (Func::new)
increment: /home/peterhuene/src/wasmtime/crates/c-api/src/func.rs:91 (create_function)
increment: /home/peterhuene/src/wasmtime/crates/c-api/src/ref.rs:129 (wasmtime_externref_data)

decrement: /home/peterhuene/src/wasmtime/crates/c-api/src/ref.rs:142 (wasmtime_externref_data)
decrement: /home/peterhuene/src/wasmtime/crates/c-api/src/func.rs:105 (create_function)
decrement: /home/peterhuene/src/wasmtime/crates/wasmtime/src/func.rs:311 (Func::new)
decrement: /home/peterhuene/src/wasmtime/crates/c-api/src/func.rs:247 (_wasmtime_func_call)

Looks like there's no matching decrement for the clone in [Func::call](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/func.rs#L597).  Still digging.

**Comment by peterhuene** [comment]
I see, I didn't expect the call parameters to end up in the activations table as the reference value is rooted by the caller to `wasm_func_call`.  This is problematic as there is no way to manually trigger the GC from the C API (afaik), not that we would want to do it after every call to `wasm_func_call` anyway.

@fitzgen thoughts on the above?

**Comment by peterhuene** [comment]
Also, should [`StoreInner::drop`](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/runtime.rs#L1166-L1172) do a GC?

**Comment by peterhuene** [comment]
I deleted the previous comment regarding a leak on dropping the store; there was actually a reference to the store alive from the .NET side because a `Dispose` call was missing.  When the store drops, the extern ref is finalized as expected.

**Comment by fitzgen** [comment]
We can add a `wasmtime.h` function to do GC, or you can pass in a bunch of references into Wasm in a loop until GC is triggered.

FWIW, I didn't test GC reclaimation in `wasmtime-py`, since we have some tests for that in Rust, but on further reflection it probably does make sense to test the interaction with host objects and finalization.

**Comment by fitzgen** [comment]
> Also, should [`StoreInner::drop`](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/runtime.rs#L1166-L1172) do a GC?
> 
> I ask because the extern ref is definitely leaked even if it's in the activation table when the store gets dropped by the host.

This is interesting, I would expect that it would be cleaned up via the activations table running `Drop`s on its elements. I'll see if I can make a Rust-only reproducer for this.

**Comment by fitzgen** [comment]
Here is a PR to add a C API to do GC: https://github.com/bytecodealliance/wasmtime/pull/2052

**Comment by peterhuene** [comment]
For my understanding, why are `wasm_func_call` arguments put in the activation table?  Given the extern refs don't end up in a table or a global in this case, it is a little surprising to me that Wasmtime itself would keep a reference alive independently of the target Wasm code.

I think exposing a GC-triggering method in the .NET API and letting the users manually collect if desired (they'll know best when to do so given their use case) make the most sense.

**Comment by fitzgen** [comment]
> For my understanding, why are `wasm_func_call` extern ref arguments put in the activation table? Given the extern refs don't end up in a table or a global in this case, it is a little surprising to me that Wasmtime itself would keep a reference alive independently of the target Wasm code.

Yeah, this is due to the deferred reference counting for references inside Wasm frames, where we don't actually increment/decrement the ref counts. Instead we over-eagerly keep them alive until we do a GC, when we find the precise set that need to be alive, and reclaim the references that were in the over approximation. See https://github.com/bytecodealliance/wasmtime/blob/main/crates/runtime/src/externref.rs#L61-L100 for more details.

**Comment by peterhuene** [comment]
The GC implementation makes sense.  I guess what I'm getting at is that it would be nice if there were a mechanism to determine if the arguments need to end up in the activation table for a call to `wasm_func_call`.

In this particular use case, there are no wasm frames on the stack when `wasm_func_call` is invoked.  As a result, any extern ref arguments are guaranteed to be rooted by the caller as `wasm_func_call` doesn't take ownership of the values.

Indeed, the only way to call `wasm_func_call` with an extern ref that needs to be in the activation table would be from an imported host function.  But if the host function is passed an extern ref that *wasn't* an argument to the "bottom most" `wasm_func_call` on the stack (i.e. one which has no wasm frames underneath it) then it must have come from a table or global get and thus would be in the activation table already, no?

**Comment by peterhuene** [comment]
My very-surface-level understanding of your GC implementation aside, it isn't a big deal to let the .NET users know that if they pass .NET GC heap objects into Wasm then they'll be kept alive until a Wasmtime GC is triggered, either automatically or manually.

**Comment by fitzgen** [comment]
Yeah, if the reference is going to outlive the call, then we could do that optimization. This does mean that if the Wasm doesn't need the reference after some point, and the host doesn't actually need to use the reference again, then it can't be reclaimed eagerly at the next GC.

With the `Func::wrap`/`Func::get` Rust APIs, we move the references into the call, passing ownership to Wasm. This means that references need to go into the activations table, but also that we can eagerly reclaim references during GC even when the call hasn't returned.

I'm sure the trade off favors one approach or another depending on the specifics.

**Comment by fitzgen** [comment]
Filed https://github.com/bytecodealliance/wasmtime/issues/2056 to investigate taking advantage of this

**Comment by peterhuene** [comment]
It wouldn't be possible to collect any extern refs passed to `wasm_func_call` in a automatically-triggered GC as they're always rooted in the calling (native) frame.

**Comment by peterhuene** [comment]
Sorry, I was basically just repeating myself there for no reason, so I deleted my last comment 😅.  Thanks for filing the issue!
