### ISSUE TITLE
Bump wasmtime to v20.x

### ISSUE THREAD

**Issue by xylobol** [bytecodealliance/wasmtime-dotnet#306]
New wasmtime version was released a few days ago - https://github.com/bytecodealliance/wasmtime/releases/tag/v20.0.0

I'll take a crack at doing this myself if it's something that would be accepted.

**Comment by fforjan** [comment]
I'm interested into the component model with this update, does wasmtime-dotnet support anything related to component ?

**Comment by jsturtevant** [comment]
@xylobol PR's are always welcome, I did open #314 but seems we have a few things to catch up on the project which I am working through in #315

**Comment by jsturtevant** [comment]
https://github.com/bytecodealliance/wasmtime-dotnet/releases/tag/v20.0.2

Will be release newer version (v21 and v22 pretty quickly after this)
