### ISSUE TITLE
Using wasmtime-dotnet in Azure Functions errors with 'image not found'

### ISSUE THREAD

**Issue by ChristianWeyer** [bytecodealliance/wasmtime-dotnet#33]
Hi all!

I have tried to use wasmtime-dotnet in an Azure Function.
For now, I am running this locally on macOS.

It fails when calling the HTTP-triggered function:
```
Executed 'RunWasm' (Failed, Id=f2ddeb26-1bdc-4f7c-a22c-85315832c10f)
System.Private.CoreLib: Exception while executing function: RunWasm. Wasmtime.Dotnet: Unable to load shared library 'wasmtime' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libwasmtime, 1): image not found.
```

As we can see, the runtimes are present in the bin folder:

![image](https://user-images.githubusercontent.com/888718/89176205-692cc900-d589-11ea-85d0-b20ba7982bd5.png)

Any ideas on what could be the issue?

You can see the repro here:
https://github.com/ChristianWeyer/azure-functions-wasmtime-repro

Thanks,
-Christian

**Comment by christophwille** [comment]
I tried it on my Mac, it does work unmodified (only fixing that gcd.wat needs to be copied to the output directory)

<img width="1440" alt="Screenshot 2020-08-03 at 15 49 25" src="https://user-images.githubusercontent.com/344208/89190093-3db5d880-d5a1-11ea-9f06-834fd35a75df.png">

**Comment by ChristianWeyer** [comment]
Ohhh, nice!
Well... no.... ;-) Interesting to get this sorted out on my machine then.

Thanks for the update @christophwille !

**Comment by ChristianWeyer** [comment]
This is now solved - I had to upgrade to the latest Azure Functions Core Tools on macOS.
Thanks for the hint @christophwille.
