### ISSUE TITLE
Using .wasm module built with Emscripten: unknown import: `env::emscripten_resize_heap` has not been defined

### ISSUE THREAD

**Issue by ChristianWeyer** [bytecodealliance/wasmtime-dotnet#34]
Hi there,
I get the following error when trying to run a .wasm module built with Emscripten v 1.40.1.

```
➜  wasmtime-dotnet-emscripten-repro git:(master) ✗ dotnet run
Unhandled exception. Wasmtime.WasmtimeException: unknown import: `env::emscripten_resize_heap` has not been defined
   at Wasmtime.Instance..ctor(LinkerHandle linker, Module module)
   at Wasmtime.Host.Instantiate(Module module)
   at WasmtimeTest1.Program.Main(String[] args) in /Users/christianweyer/sources/wasmtime-dotnet-emscripten-repro/Program.cs:line 14
```

A repro can be found here:
https://github.com/ChristianWeyer/wasmtime-dotnet-emscripten-repro

Any idea what could be the issue?

Thanks,
Christian

**Comment by tschneidereit** [comment]
Hi @ChristianWeyer, thank you for the report! Wasmtime (doesn't implement support for Emscripten's proprietary ABI and system interface, which `env::emscripten_resize_heap` is part of. The reasons for focusing on a new system interface, WASI, are laid out in [the announcement post](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/). Emscripten has [support for WASI](https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone), which might make this work (though I don't know the current status of that effort.)

**Comment by ChristianWeyer** [comment]
Hey @tschneidereit - that was a great hint!
I changed the build command and now it works.

(The repo is also updated).

Thanks again for your great work :-)
