### ISSUE TITLE
Question: Can we pass complex objects to a WASM function (and also out)?

### ISSUE THREAD

**Issue by ChristianWeyer** [bytecodealliance/wasmtime-dotnet#35]
Maybe I did not find the relevant example - but can we pass a complex object from .NET to a WASM function e.g. built with Emscripten?

Thanks,
-Christian

**Comment by peterhuene** [comment]
I'm not aware of the status of the implementation of the WebAssembly reference types proposal in Emscripten.

The support in the Wasmtime .NET API allows for passing any .NET reference type into WebAssembly as an `externref`, so the Wasm module needs to accept `externref` arguments and return values.

**Comment by ChristianWeyer** [comment]
Thanks Peter!
I figure we cannot pass objects by value?

**Comment by peterhuene** [comment]
Only reference types are supported currently.  Right now the API will throw if you try to define a host function with a parameter of an unsupported value type.  You may box and unbox value types manually (i.e. pass `object`), if desired, but the Wasmtime .NET API won't handle that automatically for you.

**Comment by ChristianWeyer** [comment]
Alright, thanks again. Keep up the great work :-)
