### ISSUE TITLE
No way to get access to exported memory outside of a Host callback

### ISSUE THREAD

**Issue by jazzay** [bytecodealliance/wasmtime-dotnet#40]
Inside a host defined callback we can do this:
```
host.DefineFunction("ns", "someHostFunction", (Caller caller, int data_ptr, int data_len) => {
       var mem = caller.GetMemory("memory"); 
}
```
However there is no exposed API for getting access to a memory via the instance directly like you can do within rust:
```
let memory = instance.get_memory("memory").ok_or(anyhow::format_err!("failed to find `memory` export"))?;	
```

**Comment by jazzay** [comment]
After more investigation I see that you can do this:
```
         var memory = instance.Externs.Memories.SingleOrDefault() ??
                throw new InvalidOperationException("Module must export a memory.");

	memory.WriteString(someMemoryOffset, "Hello World!");
```
As ExternMemory implements MemoryBase.

Might be nice API wise to make it consistent with Caller only via instance.

**Comment by peterhuene** [comment]
For clarity, perhaps we could add some simple properties for easier access into the `Externs` type?

Perhaps `Instance.Memories`, `Instance.Functions`, `Instance.Globals`, and `Instance.Tables` that simply `=> this.Externs.<property>`?

**Comment by peterhuene** [comment]
We could also add indexers that take a string for looking up by name rather than ordinal.
