### ISSUE TITLE
Reference types?

### ISSUE THREAD

**Issue by chilipepperhott** [bytecodealliance/wasmtime-dotnet#43]
Is there reference type support for .NET? According to [here](https://webassembly.org/roadmap/), it is supported in wasmtime. I am very new to all this, so bear with me if I am missing some basic understanding.

**Comment by tschneidereit** [comment]
It does, yes. The [examples](https://github.com/bytecodealliance/wasmtime-dotnet/tree/main/examples) directory contains code showing how to use both funcrefs and externrefs.

**Comment by peterhuene** [comment]
Thank you for the question, @chilipepperhott.  As Till mentioned, there is support for both funcrefs and externrefs in the Wasmtime for .NET API.

With `funcref`, a `Function` can be passed in and out.

For `externref`, any .NET reference type may be passed in and out.  If a host function accepts an `externref`, it will attempt to cast it to the callback argument's .NET type; a failure to do so will result in an `InvalidCastException`.

If you run into any problems or bugs with this support, please let us know.  For now, I'm going to close this issue, but feel free to reopen if you run into trouble.  Thanks!
