### ISSUE TITLE
wasmtime version bump

### ISSUE THREAD

**Issue by willhausman** [bytecodealliance/wasmtime-dotnet#47]
Is there additional work which needs to be accomplished before wasmtime-dotnet can be upgraded to match the current wasmtime version?  Is there a way to see what needs to be accomplished?

What version progress needs to happen before the NuGet package can come out of preview?

**Comment by peterhuene** [comment]
I'll get the missing NuGet packages published today.

The packages contain the `-preview` tag simply to denote that Wasmtime hasn't reached a 1.0 release; that is when Wasmtime will start of honoring minor version changes for semantic versioning.

The plan is to drop the tag once Wasmtime hits 1.0.

**Comment by willhausman** [comment]
Great, thanks for the information!

**Comment by peterhuene** [comment]
Hi @willhausman.  I've published 0.21.0 and 0.22.0 to NuGet.

Please let me know if you run into any problems.  For now I'll close this issue.

Thanks!
