### ISSUE TITLE
Improve debuggability by adding original host function exceptions to TrapException 

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/wasmtime-dotnet#63]
Right now if a host function throws a .NET exception, the exception is caught and translated to a trap representation.

The trap representation only keeps the exception message.  When the trap bubbles back up to .NET, the trap is thrown as a `TrapException`.

Since only the message is kept, debugging the source of the host function exception can be difficult, especially from a log that prints only the `TrapException`.

When a trap representation is created, the original caught exception should be stored somewhere that can be utilized from where `TrapException` is thrown and passed in as the inner exception.

**Comment by alexhiggins732** [comment]
I am currently in this area of code in PR #95 and not sure what else can be done here.

We are already capturing the web assembly error message as a string and work has already been done to utilize the methods within the c bindings in [trap.h](https://docs.wasmtime.dev/c-api/trap_8h.html) to walk the stack:

**Functions:**

> 
> [wasm_trap_t](https://docs.wasmtime.dev/c-api/structwasm__trap__t.html) * 	[wasmtime_trap_new](https://docs.wasmtime.dev/c-api/trap_8h.html#a6a7a1f0a53cefb2f087709044c9a4f7a) (const char *msg, size_t msg_len)
>  	Creates a new trap. [More...](https://docs.wasmtime.dev/c-api/trap_8h.html#a6a7a1f0a53cefb2f087709044c9a4f7a)
>  
> bool 	[wasmtime_trap_code](https://docs.wasmtime.dev/c-api/trap_8h.html#a6580f4f209d3eaebb6e8b9a901a30b7a) (const [wasm_trap_t](https://docs.wasmtime.dev/c-api/structwasm__trap__t.html) *, [wasmtime_trap_code_t](https://docs.wasmtime.dev/c-api/trap_8h.html#adac396a6f59222fed7a8a58b3c38e8d7) *code)
>  	Attempts to extract the trap code from this trap. [More...](https://docs.wasmtime.dev/c-api/trap_8h.html#a6580f4f209d3eaebb6e8b9a901a30b7a)
>  
> bool 	[wasmtime_trap_exit_status](https://docs.wasmtime.dev/c-api/trap_8h.html#aba323194c90dfbbbc9ad831b7ff39ca0) (const [wasm_trap_t](https://docs.wasmtime.dev/c-api/structwasm__trap__t.html) *, int *status)
>  	Attempts to extract a WASI-specific exit status from this trap. [More...](https://docs.wasmtime.dev/c-api/trap_8h.html#aba323194c90dfbbbc9ad831b7ff39ca0)
>  
> const [wasm_name_t](https://docs.wasmtime.dev/c-api/wasm_8h.html#a5a6e9ac85b29c62a9fb679a974a7cdaa) * 	[wasmtime_frame_func_name](https://docs.wasmtime.dev/c-api/trap_8h.html#aa04796738cbeaf73e9ab19c4e3b98180) (const [wasm_frame_t](https://docs.wasmtime.dev/c-api/structwasm__frame__t.html) *)
>  	Returns a human-readable name for this frame's function. [More...](https://docs.wasmtime.dev/c-api/trap_8h.html#aa04796738cbeaf73e9ab19c4e3b98180)
>  
> const [wasm_name_t](https://docs.wasmtime.dev/c-api/wasm_8h.html#a5a6e9ac85b29c62a9fb679a974a7cdaa) * 	[wasmtime_frame_module_name](https://docs.wasmtime.dev/c-api/trap_8h.html#a619bc68f00680f408826c429bfb26aba) (const [wasm_frame_t](https://docs.wasmtime.dev/c-api/structwasm__frame__t.html) *)
>  	Returns a human-readable name for this frame's module. [More...](https://docs.wasmtime.dev/c-api/trap_8h.html#a619bc68f00680f408826c429bfb26aba)
 

Please let me know if there was something else you had in mind.
