### ISSUE TITLE
Store threads

### ISSUE THREAD

**Issue by willhausman** [bytecodealliance/wasmtime-dotnet#89]
https://github.com/bytecodealliance/wasmtime-dotnet/blob/main/src/Store.cs#L162-L165

Can I get some clarification on this comment? Can I just wrap any operations I use on Store with a `lock`, or is there something more nefarious at work?  If I can just use a `lock`, is that something this library can handle itself so calling code doesn't get caught unawares by that quirk?

**Comment by peterhuene** [comment]
`Store` (and all objects attached to a store, such as instances) are safe to _send_ to another thread, meaning `Store`, and its related objects, have no thread-affinity in its internal state. However, that doesn't imply thread safety: a `Store`, and its related objects, cannot be _shared_ between multiple threads simultaneously as no locking is implemented internally.

Given that Wasmtime currently does not support creating threads from WebAssembly, making `Store` thread-safe hasn't been a priority for the runtime.

You may try to wrap operations on `Store` with a lock, but the lock must also be held when executing WebAssembly code (i.e. `Function.Invoke`) as the execution of WebAssembly itself may alter state relating to the store (keep in mind that host code also might be executed by WebAssembly via the imports given at instantiation).  It's probably quite tricky to get right.

For my better understanding, could you perhaps outline your use-case for needing to share a store between threads?

**Comment by willhausman** [comment]
Closing in favor of #90. It's the exact use case I'm thinking about, but didn't realize it was already an open issue.
